##    Copyright (c) 2025 Rich Bell <bellrichm@gmail.com>
##    See the file LICENSE.txt for your full rights.
    
    #*
    $day.lightning_strike_count.sum

    $day.lightning_min_distance.min
    $day.lightning_min_det_time.min

    $day.lightning_last_distance.last
    $day.lightning_last_det_time.last
    *#
    $alltime.lightning_min_distance.min<br>
    $alltime.lightning_min_det_time.min<br>